---
title: "dpylr.rmd"
author: "I-Ting Yu"
date: "August 21, 2016"
output: html_document
---
* .rds, R data source
```{r}
library(dplyr)
fileURL <- "https://github.com/DataScienceSpecialization/courses/blob/master/03_GettingData/dplyr/chicago.rds?raw=true"
download.file(fileURL, destfile = "./data/chicago.rds", method = "curl", extra='-L')
chicago <- readRDS("./data/chicago.rds")
```

```{r}
str(chicago)
names(chicago)
```


### select()
```{r}
head(chicago)

# From one column to another column
head(select(chicago, city:date))

# Exclude columns using "-"
head(select(chicago, -(city:dptp)))

# If not using dplyr. Done it regular way
# table, a vector which values to be matched against.
i <- match("city", table = names(chicago))
j <- match("dptp", table = names(chicago))
head(chicago[, -(i:j)])
```

### filter()
```{r}
chic.f <- filter(chicago, pm25tmean2 > 30)
head(chic.f)
chic.f <- filter(chicago, pm25tmean2 > 30 & tmpd > 80)
head(chic.f)
```

### arrange()
```{r}
chicago <- arrange(chicago, date)
head(chicago)
tail(chicago)

chicago <- arrange(chicago, desc(date))
head(chicago)
```

### rename()
```{r}
chicago <- rename(chicago, pm25 = pm25tmean2, dewpoint = dptp)
head(chicago)
```

### mutate()
```{r}
chicago <- mutate(chicago, pm25detrend = pm25 - mean(pm25, na.rm = TRUE))
head(select(chicago, pm25, pm25detrend))
```

### group_by()
To apply summarize later
```{r}
chicago <- mutate(chicago, tempcat = factor(1 * (tmpd > 80), labels = c("cold", "hot")))
head(chicago)

hotcold <- group_by(chicago, tempcat)
hotcold

```

### summarise(), summarize()
```{r}
summarize(hotcold, pm25 = mean(pm25, na.rm = TRUE), o3 = max(o3tmean2), no2 = median(no2tmean2))

tmp <- unclass(as.POSIXlt(chicago$date))$year
chicago <- mutate(chicago, year = tmp+ 1900)

years <- group_by(chicago, year)
head(years)
class(years)
summarize(years, pm25 = mean(pm25, na.rm = TRUE), o3 = max(o3tmean2), no2 = median(no2tmean2))
summarize(years, count = n())
```

### %>% (pipeline operator)
Advantage: No need to create temporary variables
```{r}
chicago %>% mutate(month = as.POSIXlt(date)$mon + 1) %>% group_by(month) %>% summarize(pm25 = mean(pm25, na.rm = TRUE), o3 = max(o3tmean2), no2 = median(no2tmean2))

```

### Thoughts
* data.table is desgined for large tables
=> Use dplyr, when dealing with smaller data set and wanting to use database-like functions.

