---
title: "Reading_From_HDF5"
author: "I-Ting Yu"
date: "August 17, 2016"
output: html_document
---

#### R HDF5 Package 
Hierarchical Data Format (HDF) is a set of file formats (HDF4, HDF5) designed to store and organize large amounts of data.
```{r}
source("http://bioconductor.org/biocLite.R")
biocLite("rhdf5")
library(rhdf5)
created <- h5createFile(file = "example.h5")
created
```

#### Create Groups
```{r}
created <- h5createGroup(file = "example.h5", group = "foo")
created <- h5createGroup(file = "example.h5", group = "baa")

# subgroup
created <- h5createGroup(file = "example.h5", group = "foo/foobaa")
created

# Just like ls
h5ls("example.h5")
```

#### Write to Group
```{r}
A <- matrix(1:10, nrow = 5, ncol = 2)
h5write(obj = A, file = "example.h5", name = "foo/A")

B <- array(seq(0.1, 2.0, by = 0.1), dim = c(5, 2, 2))
# Add unit attribute to B
attr(B, "scale") <- "liter"
h5write(obj = B, file = "example.h5", name = "foo/foobaa/B")

h5ls("example.h5")

```

#### Write a Data Set
```{r}
df = data.frame(1L:5L, seq(0, 1, length.out = 5), c("ab", "cde", "fghi", "a", "s"), stringsAsFactors = FALSE)

h5write(obj = df, file = "example.h5", name = "df")

h5ls("example.h5")
```

#### Read Data
```{r}
h5read.result.A = h5read(file = "example.h5", name = "foo/A")

h5read.result.B = h5read(file = "example.h5", name = "foo/foobaa/B")

h5read.result.df = h5read(file = "example.h5", name = "df")

h5read.result.A 
```

#### Write and Read Chunks
```{r}
h5write(obj = c(12, 13, 14), file = "example.h5", name = "foo/A", index = list(1:3, 1))

h5read(file = "example.h5", name = "foo/A")
```




